### ISSUE TITLE
Error running npx cap sync / npm install pushy-cordova after updating node, XCode, et al

### ISSUE THREAD

**Issue by webeditors** [pushy-me/pushy-cordova#44]
I'm revisiting a Capacitor project I haven't updated in a while (at least a year), so I've updated everything including MacOS, XCode, NodeJS, Capacitor, etc. But when I run `npx cap sync` I get the following error:

	[error] Analyzing dependencies
			[!] CocoaPods could not find compatible versions for pod "Pushy":
			In snapshot (Podfile.lock):
			Pushy (= 1.0.46, ~> 1.0.32)
			
			In Podfile:
			CordovaPluginsStatic (from `../capacitor-cordova-ios-plugins`) was
			resolved to 5.7.8, which depends on
			Pushy (~> 1.0.53)
			
			Specs satisfying the `Pushy (= 1.0.46, ~> 1.0.32), Pushy (~> 1.0.53)`
			dependency were found, but they required a higher minimum deployment
			target.

If I try to update Pushy by running `npm install pushy-cordova` I get this error:

	npm error Cannot destructure property 'package' of 'node.target' as it is null.

Any ideas what's going wrong here?

**Comment by pushy** [comment]
Hi @webeditors,
Thanks for reaching out. We'd be glad to assist with your inquiry.

Based on the error `Specs satisfying the Pushy (= 1.0.46, ~> 1.0.32), Pushy (~> 1.0.53) dependency were found, but they required a higher minimum deployment target.`, it appears that your Xcode project's minimum deployment target is set too low. 

Please update your `Podfile` and set the `platform :ios` parameter to `9.0` as follows:

```
platform :ios, '9.0'
```

Then, save the file and run `pod install` again, and the error should be resolved.

Please let us know if there's anything else we can help with.

**Comment by webeditors** [comment]
Ok, tried that (it was set to `platform :ios, '13.0'`) but still giving the same error.

Any other suggestions?

**Comment by pushy** [comment]
Hi @webeditors,
Try deleting your `Podfile.lock`, and then run `pod install` again.

**Comment by webeditors** [comment]
Ok, still no change.

Just so I'm understanding, the dependancy is for v1.0.53 and I have v1.0.59, but you thing this is to do with deployment target and nothing to do with the version of pushy I have installed? In XCode 16, the default deployment targets appear to be 15 thru 18 - should I got through everything that has 13 as the target and update it to 15, or am I chasing a red herring?

**Comment by webeditors** [comment]
Ah... fixed it.

The solution was to get into the App folder, then run `pod update Pushy` - now I can `npx cap sync` with no errors.

**Comment by pushy** [comment]
Glad to hear you managed to find a solution! 👍
